version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_password
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
